export const ADD_TITULAR = 'ADD_TITULAR';
export const ADD_SUPLENTE = 'ADD_SUPLENTE';
export const DELETE_TITULAR = 'DELETE_TITULAR';
export const DELETE_SUPLENTE = 'DELETE_SUPLENTE';
export const DEFAULT_CONSTANT = 'DEFAULT_CONSTANT';
